language: node_js
node_js:
  - "stable"
before_script:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  local_dir: docs/
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master
