language: node_js
dist: xenial
os: linux
node_js:
  - "stable"
before_script:
  - yarn install
script:
  - yarn build
deploy:
  strategy: git
  provider: pages
  local_dir: docs/
  token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master