language: node_js
node_js:
  - "stable"
before_script:
  - yarn install
script:
  - yarn build
  - yarn generate
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  target_branch: gh-pages
  local_dir: dist
  on:
    branch: master
