name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  bump:
    name: Release & Bump version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Bump version and create changelog
        if: "!startsWith(github.event.head_commit.message, 'chore(release)')"
        run: |
          git config --local user.name "ElianCodes"
          git config --local user.email "hello@elian.codes"
          npx standard-version -a

      - name: Push changes and tags
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          remote_repo="https://${GITHUB_ACTOR}:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git pull $remote_repo $CURRENT_BRANCH
          git push $remote_repo HEAD:$CURRENT_BRANCH --follow-tags --tags
